server:
  port: 8080

spring:
  application:
    name: spring-batch
  datasource:
    url: jdbc:mysql://8.142.8.135:3306/crawlab_xencio?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: c4c_watson_w
    password: Watson@2021@#%
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/xencio/marquez/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl